server:
  port: 9889

spring:
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always


